//! Lightweight bit-reader types and Golomb-Rice decoding primitives.
//!
//! Shared by both the Huffman and tANS decoders for frequency-table
//! reading.  Kept separate from `io/BitReader.zig` (which carries
//! distance/length/gamma methods) so the entropy hot paths pull in
//! only the minimal API they need.

const std = @import("std");

// ────────────────────────────────────────────────────────────
//  Data structures
// ────────────────────────────────────────────────────────────

/// MSB-first, forward-refill bit reader for table headers.
pub const BitReaderState = struct {
    p: [*]const u8,
    p_end: [*]const u8,
    bits: u32,
    bit_pos: i32,
};

/// Secondary byte-aligned reader used by Golomb-Rice decoding.
pub const BitReader2 = struct {
    p: [*]const u8,
    p_end: [*]const u8,
    bit_pos: u32,
};

/// Symbol range produced by `huffConvertToRanges`.
pub const HuffRange = struct {
    symbol: u16,
    num: u16,
};

pub const DecodeError = error{
    CorruptStream,
    SourceTruncated,
    OutputTruncated,
    BadCodeLengthFormat,
    InvalidCodeLength,
    InvalidRanges,
    LutConstructionFailed,
    StreamMismatch,
};

// ────────────────────────────────────────────────────────────
//  Golomb-Rice decode tables
// ────────────────────────────────────────────────────────────

/// Pre-computed Golomb-Rice decoding table (value half). Entry `i` packs up to
/// four 4-bit symbols in the low nibbles and a carry count in the high nibble
/// of the MSB. Generated by enumerating all 256 possible 8-bit prefix patterns
/// for Rice parameter k=2.
pub const k_rice_code_bits2_value = [_]u32{
    0x80000000, 0x00000007, 0x10000006, 0x00000006, 0x20000005, 0x00000105, 0x10000005, 0x00000005,
    0x30000004, 0x00000204, 0x10000104, 0x00000104, 0x20000004, 0x00010004, 0x10000004, 0x00000004,
    0x40000003, 0x00000303, 0x10000203, 0x00000203, 0x20000103, 0x00010103, 0x10000103, 0x00000103,
    0x30000003, 0x00020003, 0x10010003, 0x00010003, 0x20000003, 0x01000003, 0x10000003, 0x00000003,
    0x50000002, 0x00000402, 0x10000302, 0x00000302, 0x20000202, 0x00010202, 0x10000202, 0x00000202,
    0x30000102, 0x00020102, 0x10010102, 0x00010102, 0x20000102, 0x01000102, 0x10000102, 0x00000102,
    0x40000002, 0x00030002, 0x10020002, 0x00020002, 0x20010002, 0x01010002, 0x10010002, 0x00010002,
    0x30000002, 0x02000002, 0x11000002, 0x01000002, 0x20000002, 0x00000012, 0x10000002, 0x00000002,
    0x60000001, 0x00000501, 0x10000401, 0x00000401, 0x20000301, 0x00010301, 0x10000301, 0x00000301,
    0x30000201, 0x00020201, 0x10010201, 0x00010201, 0x20000201, 0x01000201, 0x10000201, 0x00000201,
    0x40000101, 0x00030101, 0x10020101, 0x00020101, 0x20010101, 0x01010101, 0x10010101, 0x00010101,
    0x30000101, 0x02000101, 0x11000101, 0x01000101, 0x20000101, 0x00000111, 0x10000101, 0x00000101,
    0x50000001, 0x00040001, 0x10030001, 0x00030001, 0x20020001, 0x01020001, 0x10020001, 0x00020001,
    0x30010001, 0x02010001, 0x11010001, 0x01010001, 0x20010001, 0x00010011, 0x10010001, 0x00010001,
    0x40000001, 0x03000001, 0x12000001, 0x02000001, 0x21000001, 0x01000011, 0x11000001, 0x01000001,
    0x30000001, 0x00000021, 0x10000011, 0x00000011, 0x20000001, 0x00001001, 0x10000001, 0x00000001,
    0x70000000, 0x00000600, 0x10000500, 0x00000500, 0x20000400, 0x00010400, 0x10000400, 0x00000400,
    0x30000300, 0x00020300, 0x10010300, 0x00010300, 0x20000300, 0x01000300, 0x10000300, 0x00000300,
    0x40000200, 0x00030200, 0x10020200, 0x00020200, 0x20010200, 0x01010200, 0x10010200, 0x00010200,
    0x30000200, 0x02000200, 0x11000200, 0x01000200, 0x20000200, 0x00000210, 0x10000200, 0x00000200,
    0x50000100, 0x00040100, 0x10030100, 0x00030100, 0x20020100, 0x01020100, 0x10020100, 0x00020100,
    0x30010100, 0x02010100, 0x11010100, 0x01010100, 0x20010100, 0x00010110, 0x10010100, 0x00010100,
    0x40000100, 0x03000100, 0x12000100, 0x02000100, 0x21000100, 0x01000110, 0x11000100, 0x01000100,
    0x30000100, 0x00000120, 0x10000110, 0x00000110, 0x20000100, 0x00001100, 0x10000100, 0x00000100,
    0x60000000, 0x00050000, 0x10040000, 0x00040000, 0x20030000, 0x01030000, 0x10030000, 0x00030000,
    0x30020000, 0x02020000, 0x11020000, 0x01020000, 0x20020000, 0x00020010, 0x10020000, 0x00020000,
    0x40010000, 0x03010000, 0x12010000, 0x02010000, 0x21010000, 0x01010010, 0x11010000, 0x01010000,
    0x30010000, 0x00010020, 0x10010010, 0x00010010, 0x20010000, 0x00011000, 0x10010000, 0x00010000,
    0x50000000, 0x04000000, 0x13000000, 0x03000000, 0x22000000, 0x02000010, 0x12000000, 0x02000000,
    0x31000000, 0x01000020, 0x11000010, 0x01000010, 0x21000000, 0x01001000, 0x11000000, 0x01000000,
    0x40000000, 0x00000030, 0x10000020, 0x00000020, 0x20000010, 0x00001010, 0x10000010, 0x00000010,
    0x30000000, 0x00002000, 0x10001000, 0x00001000, 0x20000000, 0x00100000, 0x10000000, 0x00000000,
};

/// Pre-computed Golomb-Rice decoding table (length half). Paired with
/// `k_rice_code_bits2_value`.
pub const k_rice_code_bits2_len = [_]u8{
    0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4, 1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5,
    1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
    1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
    2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
    1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
    2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
    2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
    3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7, 4, 5, 5, 6, 5, 6, 6, 7, 5, 6, 6, 7, 6, 7, 7, 8,
};

// ────────────────────────────────────────────────────────────
//  BitReaderState helpers (MSB-first, forward refill)
// ────────────────────────────────────────────────────────────

pub inline fn bitReaderRefill(br: *BitReaderState) void {
    while (br.bit_pos > 0) {
        const byte: u32 = if (@intFromPtr(br.p) < @intFromPtr(br.p_end)) br.p[0] else 0;
        br.bits |= byte << @intCast(br.bit_pos);
        br.bit_pos -= 8;
        br.p += 1;
    }
}

pub inline fn bitReaderReadBit(br: *BitReaderState) u32 {
    bitReaderRefill(br);
    const r = br.bits >> 31;
    br.bits <<= 1;
    br.bit_pos += 1;
    return r;
}

pub inline fn bitReaderReadBitNoRefill(br: *BitReaderState) u32 {
    const r = br.bits >> 31;
    br.bits <<= 1;
    br.bit_pos += 1;
    return r;
}

/// Reads `n` bits (n >= 1) without refilling.
pub inline fn bitReaderReadBitsNoRefill(br: *BitReaderState, n: u5) u32 {
    std.debug.assert(n >= 1);
    const r = br.bits >> @intCast(32 - @as(u6, n));
    br.bits <<= n;
    br.bit_pos += n;
    return r;
}

/// Reads `n` bits without refilling; `n` may be zero. Uses the two-shift
/// trick to dodge the undefined shift-by-32 case.
pub inline fn bitReaderReadBitsNoRefillZero(br: *BitReaderState, n: u6) u32 {
    if (n == 0) return 0;
    const r = (br.bits >> 1) >> @intCast(31 - n);
    br.bits <<= @intCast(n);
    br.bit_pos += @intCast(n);
    return r;
}

/// Reads the "fluff" encoding for alphabets with fewer than 256 symbols.
pub fn bitReaderReadFluff(br: *BitReaderState, num_symbols: u32) u32 {
    if (num_symbols == 256) return 0;
    var x: u32 = 257 - num_symbols;
    if (x > num_symbols) x = num_symbols;
    x *= 2;

    const y: u32 = std.math.log2_int(u32, x - 1) + 1;
    const v: u32 = br.bits >> @intCast(32 - y);
    const z: u32 = (@as(u32, 1) << @intCast(y)) - x;

    if ((v >> 1) >= z) {
        br.bits <<= @intCast(y);
        br.bit_pos += @intCast(y);
        return v - z;
    } else {
        br.bits <<= @intCast(y - 1);
        br.bit_pos += @intCast(y - 1);
        return v >> 1;
    }
}

// ────────────────────────────────────────────────────────────
//  Golomb-Rice decoding
// ────────────────────────────────────────────────────────────

/// Decodes Golomb-Rice run lengths from a bit stream.
pub fn decodeGolombRiceLengths(dst_buf: [*]u8, size: usize, br: *BitReader2) DecodeError!void {
    var p = br.p;
    const p_end = br.p_end;
    var dst = dst_buf;
    const dst_end = dst_buf + size;

    if (@intFromPtr(p) >= @intFromPtr(p_end)) return error.SourceTruncated;

    var count: i32 = -@as(i32, @intCast(br.bit_pos));
    const initial_mask: u32 = @as(u32, 255) >> @intCast(br.bit_pos);
    var v: u32 = p[0] & initial_mask;
    p += 1;

    while (true) {
        if (v == 0) {
            count += 8;
        } else {
            const x = k_rice_code_bits2_value[v];
            // Store count + low-nibble symbols at dst[0..4]. `count` is small
            // (may be slightly negative); byte-wise the math must wrap.
            const lo: u32 = @as(u32, @bitCast(count)) +% (x & 0x0F0F_0F0F);
            const hi: u32 = (x >> 4) & 0x0F0F_0F0F;
            std.mem.writeInt(u32, dst[0..4], lo, .little);
            std.mem.writeInt(u32, dst[4..8], hi, .little);
            dst += k_rice_code_bits2_len[v];
            if (@intFromPtr(dst) >= @intFromPtr(dst_end)) break;
            count = @intCast(x >> 28);
        }
        if (@intFromPtr(p) >= @intFromPtr(p_end)) return error.SourceTruncated;
        v = p[0];
        p += 1;
    }

    // Overshoot correction: step back by dropping trailing set bits from v.
    if (@intFromPtr(dst) > @intFromPtr(dst_end)) {
        var n: usize = @intFromPtr(dst) - @intFromPtr(dst_end);
        while (n != 0) : (n -= 1) {
            v &= v - 1;
        }
    }

    var bit_pos: u32 = 0;
    if ((v & 1) == 0) {
        p -= 1;
        const q: u32 = @ctz(v);
        bit_pos = 8 - q;
    }
    br.p = p;
    br.bit_pos = bit_pos;
}

/// Decodes additional Golomb-Rice precision bits (1, 2, or 3) and merges them
/// into the length array. Uses SIMD-style bit unpacking (u64 bit manipulation
/// tricks).
pub fn decodeGolombRiceBits(dst_buf: [*]u8, size: usize, bitcount: u32, br: *BitReader2) DecodeError!void {
    if (bitcount == 0) return;

    const dst_end = dst_buf + size;
    var p = br.p;
    const p_end = br.p_end;
    const bit_pos = br.bit_pos;

    const bits_required: u32 = @intCast(bit_pos + bitcount * @as(u32, @intCast(size)));
    const bytes_required: usize = (bits_required + 7) >> 3;
    if (bytes_required > @intFromPtr(p_end) - @intFromPtr(p)) return error.SourceTruncated;

    br.p = p + (bits_required >> 3);
    br.bit_pos = bits_required & 7;

    // Caller must guarantee 8-byte padding past dst_end.
    const bak: u64 = std.mem.readInt(u64, dst_end[0..8], .little);
    var dst = dst_buf;

    switch (bitcount) {
        1 => {
            while (@intFromPtr(dst) < @intFromPtr(dst_end)) {
                const raw: u32 = @byteSwap(std.mem.readInt(u32, p[0..4], .little));
                var bits: u64 = @as(u8, @truncate(raw >> @intCast(24 - bit_pos)));
                p += 1;
                bits = (bits | (bits << 28)) & 0x0F0000_000F;
                bits = (bits | (bits << 14)) & 0x0003_0003_0003_0003;
                bits = (bits | (bits << 7)) & 0x0101_0101_0101_0101;
                const prev = std.mem.readInt(u64, dst[0..8], .little);
                const result = prev * 2 + @byteSwap(bits);
                std.mem.writeInt(u64, dst[0..8], result, .little);
                dst += 8;
            }
        },
        2 => {
            while (@intFromPtr(dst) < @intFromPtr(dst_end)) {
                const raw: u32 = @byteSwap(std.mem.readInt(u32, p[0..4], .little));
                var bits: u64 = @as(u16, @truncate(raw >> @intCast(16 - bit_pos)));
                p += 2;
                bits = (bits | (bits << 24)) & 0x00FF_0000_00FF;
                bits = (bits | (bits << 12)) & 0x000F_000F_000F_000F;
                bits = (bits | (bits << 6)) & 0x0303_0303_0303_0303;
                const prev = std.mem.readInt(u64, dst[0..8], .little);
                const result = prev * 4 + @byteSwap(bits);
                std.mem.writeInt(u64, dst[0..8], result, .little);
                dst += 8;
            }
        },
        else => { // bitcount == 3
            while (@intFromPtr(dst) < @intFromPtr(dst_end)) {
                const raw: u32 = @byteSwap(std.mem.readInt(u32, p[0..4], .little));
                var bits: u64 = (raw >> @intCast(8 - bit_pos)) & 0xFFFFFF;
                p += 3;
                bits = (bits | (bits << 20)) & 0x0FFF_0000_0FFF;
                bits = (bits | (bits << 10)) & 0x003F_003F_003F_003F;
                bits = (bits | (bits << 5)) & 0x0707_0707_0707_0707;
                const prev = std.mem.readInt(u64, dst[0..8], .little);
                const result = prev * 8 + @byteSwap(bits);
                std.mem.writeInt(u64, dst[0..8], result, .little);
                dst += 8;
            }
        },
    }

    std.mem.writeInt(u64, dst_end[0..8], bak, .little);
}

// ────────────────────────────────────────────────────────────
//  Range conversion
// ────────────────────────────────────────────────────────────

pub fn huffConvertToRanges(
    ranges: [*]HuffRange,
    num_symbols: u32,
    p_fluff: u32,
    symlen_in: [*]const u8,
    br: *BitReaderState,
) DecodeError!u32 {
    const num_ranges: u32 = p_fluff >> 1;
    var sym_idx: i32 = 0;
    var symlen = symlen_in;

    if ((p_fluff & 1) != 0) {
        bitReaderRefill(br);
        const v: u32 = symlen[0];
        symlen += 1;
        if (v >= 8) return error.BadCodeLengthFormat;
        const extra: u5 = @intCast(v + 1);
        sym_idx = @intCast(bitReaderReadBitsNoRefill(br, extra) + (@as(u32, 1) << extra) - 1);
    }

    var syms_used: u32 = 0;
    var i: u32 = 0;
    while (i < num_ranges) : (i += 1) {
        bitReaderRefill(br);
        const v0: u32 = symlen[0];
        if (v0 >= 9) return error.BadCodeLengthFormat;
        const v0_u5: u6 = @intCast(v0);
        const num = bitReaderReadBitsNoRefillZero(br, v0_u5) + (@as(u32, 1) << @intCast(v0));
        const v1: u32 = symlen[1];
        if (v1 >= 8) return error.BadCodeLengthFormat;
        const v1_u5: u5 = @intCast(v1 + 1);
        const space = bitReaderReadBitsNoRefill(br, v1_u5) + (@as(u32, 1) << v1_u5) - 1;
        ranges[i] = .{ .symbol = @intCast(sym_idx), .num = @intCast(num) };
        syms_used += num;
        sym_idx += @intCast(num + space);
        symlen += 2;
    }

    if (sym_idx >= 256 or syms_used >= num_symbols or
        @as(u32, @intCast(sym_idx)) + num_symbols - syms_used > 256)
    {
        return error.InvalidRanges;
    }
    ranges[num_ranges] = .{ .symbol = @intCast(sym_idx), .num = @intCast(num_symbols - syms_used) };
    return num_ranges + 1;
}

// ────────────────────────────────────────────────────────────
//  Tests
// ────────────────────────────────────────────────────────────

const testing = std.testing;

test "k_rice_code_bits2_value matches reference table length" {
    try testing.expectEqual(@as(usize, 256), k_rice_code_bits2_value.len);
    try testing.expectEqual(@as(u32, 0x80000000), k_rice_code_bits2_value[0]);
    try testing.expectEqual(@as(u32, 0x00000000), k_rice_code_bits2_value[255]);
}

test "k_rice_code_bits2_len matches reference table" {
    try testing.expectEqual(@as(usize, 256), k_rice_code_bits2_len.len);
    try testing.expectEqual(@as(u8, 0), k_rice_code_bits2_len[0]);
    try testing.expectEqual(@as(u8, 8), k_rice_code_bits2_len[255]);
}

test "bitReaderRefill forward mirrors io/bit_reader" {
    const data = [_]u8{ 0xAB, 0xCD, 0xEF, 0x12 };
    var br: BitReaderState = .{ .p = data[0..].ptr, .p_end = data[0..].ptr + data.len, .bits = 0, .bit_pos = 24 };
    bitReaderRefill(&br);
    try testing.expectEqual(@as(u32, 0xABCDEF00), br.bits);
    try testing.expectEqual(@as(i32, 0), br.bit_pos);
}
