// Huffman decoding functions.

using System.Buffers.Binary;
using System.IO;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;

namespace StreamLZ.Decompression.Entropy;

/// <summary>
/// Huffman-based entropy decoder.
/// Handles 3-stream parallel Huffman decoding with 11-bit LUT.
/// </summary>
internal static unsafe partial class HuffmanDecoder
{
    /// <summary>
    /// Range entry used during Huffman code-length table construction.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct HuffRange
    {
        public ushort Symbol;
        public ushort Num;
    }

    // HuffRevLut and NewHuffLut are defined in Common/Types.cs (top-level types).

    /// <summary>
    /// State for the 3-stream parallel Huffman decoder.
    /// Two forward streams (src, src_mid) and one backward stream (src_end).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct HuffReader
    {
        public byte* Output;
        public byte* OutputEnd;
        public byte* Src;
        public byte* SrcMid;
        public byte* SrcEnd;
        public byte* SrcMidOrg;
        public int SrcBitpos;
        public int SrcMidBitpos;
        public int SrcEndBitpos;
        public uint SrcBits;
        public uint SrcMidBits;
        public uint SrcEndBits;
    }

    /// <summary>
    /// Secondary bit reader used by Golomb-Rice decoding.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct BitReader2
    {
        public byte* P;
        public byte* PEnd;
        public uint Bitpos;
    }

    #region Lookup Tables

    /// <summary>
    /// Pre-computed Golomb-Rice decoding table (value half). Entry i decodes a 2-bit
    /// Rice code pair: the low nibbles of each byte in the packed uint hold the decoded
    /// symbol values, and the high nibble of the most-significant byte holds a carry
    /// count for bits that span into the next byte. Generated by enumerating all 256
    /// possible 8-bit prefix patterns for Rice parameter k=2.
    /// </summary>
    private static ReadOnlySpan<uint> KRiceCodeBits2Value =>
    [
        0x80000000, 0x00000007, 0x10000006, 0x00000006, 0x20000005, 0x00000105, 0x10000005, 0x00000005,
        0x30000004, 0x00000204, 0x10000104, 0x00000104, 0x20000004, 0x00010004, 0x10000004, 0x00000004,
        0x40000003, 0x00000303, 0x10000203, 0x00000203, 0x20000103, 0x00010103, 0x10000103, 0x00000103,
        0x30000003, 0x00020003, 0x10010003, 0x00010003, 0x20000003, 0x01000003, 0x10000003, 0x00000003,
        0x50000002, 0x00000402, 0x10000302, 0x00000302, 0x20000202, 0x00010202, 0x10000202, 0x00000202,
        0x30000102, 0x00020102, 0x10010102, 0x00010102, 0x20000102, 0x01000102, 0x10000102, 0x00000102,
        0x40000002, 0x00030002, 0x10020002, 0x00020002, 0x20010002, 0x01010002, 0x10010002, 0x00010002,
        0x30000002, 0x02000002, 0x11000002, 0x01000002, 0x20000002, 0x00000012, 0x10000002, 0x00000002,
        0x60000001, 0x00000501, 0x10000401, 0x00000401, 0x20000301, 0x00010301, 0x10000301, 0x00000301,
        0x30000201, 0x00020201, 0x10010201, 0x00010201, 0x20000201, 0x01000201, 0x10000201, 0x00000201,
        0x40000101, 0x00030101, 0x10020101, 0x00020101, 0x20010101, 0x01010101, 0x10010101, 0x00010101,
        0x30000101, 0x02000101, 0x11000101, 0x01000101, 0x20000101, 0x00000111, 0x10000101, 0x00000101,
        0x50000001, 0x00040001, 0x10030001, 0x00030001, 0x20020001, 0x01020001, 0x10020001, 0x00020001,
        0x30010001, 0x02010001, 0x11010001, 0x01010001, 0x20010001, 0x00010011, 0x10010001, 0x00010001,
        0x40000001, 0x03000001, 0x12000001, 0x02000001, 0x21000001, 0x01000011, 0x11000001, 0x01000001,
        0x30000001, 0x00000021, 0x10000011, 0x00000011, 0x20000001, 0x00001001, 0x10000001, 0x00000001,
        0x70000000, 0x00000600, 0x10000500, 0x00000500, 0x20000400, 0x00010400, 0x10000400, 0x00000400,
        0x30000300, 0x00020300, 0x10010300, 0x00010300, 0x20000300, 0x01000300, 0x10000300, 0x00000300,
        0x40000200, 0x00030200, 0x10020200, 0x00020200, 0x20010200, 0x01010200, 0x10010200, 0x00010200,
        0x30000200, 0x02000200, 0x11000200, 0x01000200, 0x20000200, 0x00000210, 0x10000200, 0x00000200,
        0x50000100, 0x00040100, 0x10030100, 0x00030100, 0x20020100, 0x01020100, 0x10020100, 0x00020100,
        0x30010100, 0x02010100, 0x11010100, 0x01010100, 0x20010100, 0x00010110, 0x10010100, 0x00010100,
        0x40000100, 0x03000100, 0x12000100, 0x02000100, 0x21000100, 0x01000110, 0x11000100, 0x01000100,
        0x30000100, 0x00000120, 0x10000110, 0x00000110, 0x20000100, 0x00001100, 0x10000100, 0x00000100,
        0x60000000, 0x00050000, 0x10040000, 0x00040000, 0x20030000, 0x01030000, 0x10030000, 0x00030000,
        0x30020000, 0x02020000, 0x11020000, 0x01020000, 0x20020000, 0x00020010, 0x10020000, 0x00020000,
        0x40010000, 0x03010000, 0x12010000, 0x02010000, 0x21010000, 0x01010010, 0x11010000, 0x01010000,
        0x30010000, 0x00010020, 0x10010010, 0x00010010, 0x20010000, 0x00011000, 0x10010000, 0x00010000,
        0x50000000, 0x04000000, 0x13000000, 0x03000000, 0x22000000, 0x02000010, 0x12000000, 0x02000000,
        0x31000000, 0x01000020, 0x11000010, 0x01000010, 0x21000000, 0x01001000, 0x11000000, 0x01000000,
        0x40000000, 0x00000030, 0x10000020, 0x00000020, 0x20000010, 0x00001010, 0x10000010, 0x00000010,
        0x30000000, 0x00002000, 0x10001000, 0x00001000, 0x20000000, 0x00100000, 0x10000000, 0x00000000,
    ];

    /// <summary>
    /// Pre-computed Golomb-Rice decoding table (length half). Entry i gives the number
    /// of complete symbols decoded from the 8-bit prefix pattern i using Rice parameter
    /// k=2. Paired with <see cref="KRiceCodeBits2Value"/>: Value[i] holds the decoded
    /// symbols, Len[i] holds how many symbols were consumed.
    /// </summary>
    private static ReadOnlySpan<byte> KRiceCodeBits2Len =>
    [
        0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4, 1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5,
        1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
        1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
        2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
        1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
        2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
        2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
        3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7, 4, 5, 5, 6, 5, 6, 6, 7, 5, 6, 6, 7, 6, 7, 7, 8,
    ];

    /// <summary>
    /// Canonical Huffman code-length prefix sums for lengths 0..11.
    /// </summary>
    public static ReadOnlySpan<uint> CodePrefixOrg =>
    [
        0x0, 0x0, 0x2, 0x6, 0xE, 0x1E, 0x3E, 0x7E, 0xFE, 0x1FE, 0x2FE, 0x3FE
    ];

    #endregion

    #region BitReader helpers

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int CountLeadingZeros(uint bits)
    {
        return BitOperations.LeadingZeroCount(bits);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void BitReader_Refill(ref BitReaderState bits)
    {
        while (bits.Bitpos > 0)
        {
            bits.Bits |= (uint)(bits.P < bits.PEnd ? *bits.P : 0) << bits.Bitpos;
            bits.Bitpos -= 8;
            bits.P++;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int BitReader_ReadBit(ref BitReaderState bits)
    {
        BitReader_Refill(ref bits);
        int r = (int)(bits.Bits >> 31);
        bits.Bits <<= 1;
        bits.Bitpos += 1;
        return r;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int BitReader_ReadBitNoRefill(ref BitReaderState bits)
    {
        int r = (int)(bits.Bits >> 31);
        bits.Bits <<= 1;
        bits.Bitpos += 1;
        return r;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int BitReader_ReadBitsNoRefill(ref BitReaderState bits, int n)
    {
        int r = (int)(bits.Bits >> (32 - n));
        bits.Bits <<= n;
        bits.Bitpos += n;
        return r;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int BitReader_ReadBitsNoRefillZero(ref BitReaderState bits, int n)
    {
        int r = (int)(bits.Bits >> 1 >> (31 - n));
        bits.Bits <<= n;
        bits.Bitpos += n;
        return r;
    }

    #endregion

    #region BitReader state struct

    /// <summary>
    /// Minimal mutable bit reader state used throughout Huffman and TANS decoding.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This struct exists separately from <see cref="Common.BitReader"/> for two reasons:
    /// </para>
    /// <list type="number">
    ///   <item>
    ///     <b>API pattern:</b> The Huffman/TANS decoders use a static-method API
    ///     (e.g. <c>BitReader_Refill(ref BitReaderState)</c>) rather than instance methods.
    ///     This keeps the hot decode loops free of indirect dispatch and allows the JIT to
    ///     inline the state into registers without struct-copy overhead.
    ///   </item>
    ///   <item>
    ///     <b>Minimal surface:</b> <see cref="Common.BitReader"/> carries additional methods
    ///     (ReadDistance, ReadLength, ReadGamma, etc.) needed by the LZ offset/length
    ///     unpacking layer. BitReaderState is intentionally stripped down to just the four
    ///     fields required by the bulk Huffman symbol decode loop, keeping the struct small
    ///     and cache-friendly.
    ///   </item>
    /// </list>
    /// <para>
    /// Note: the field is named <c>Bitpos</c> (lowercase 'p') here vs <c>BitPos</c> in
    /// Common.BitReader. Both use the same MSB-first convention where Bitpos/BitPos starts
    /// at 24 and refill loads bytes until it drops to 0 or below.
    /// </para>
    /// </remarks>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct BitReaderState
    {
        /// <summary>Current read position in the byte stream.</summary>
        public byte* P;
        /// <summary>End-of-stream sentinel (forward) or start sentinel (backward).</summary>
        public byte* PEnd;
        /// <summary>Accumulated bits; most-significant bits are consumed first.</summary>
        public uint Bits;
        /// <summary>Next byte lands at this bit position; &lt;= 0 means at least 24 valid bits.</summary>
        public int Bitpos;
    }

    #endregion

    #region ReadFluff

    /// <summary>
    /// Reads the "fluff" value that encodes range information for fewer-than-256 symbol alphabets.
    /// </summary>
    public static int BitReader_ReadFluff(ref BitReaderState bits, int numSymbols)
    {
        if (numSymbols == 256)
        {
            return 0;
        }

        int x = 257 - numSymbols;
        if (x > numSymbols)
        {
            x = numSymbols;
        }

        x *= 2;

        uint y = (uint)BitOperations.Log2((uint)(x - 1)) + 1;

        uint v = bits.Bits >> (int)(32 - y);
        uint z = (1u << (int)y) - (uint)x;

        if ((v >> 1) >= z)
        {
            bits.Bits <<= (int)y;
            bits.Bitpos += (int)y;
            return (int)(v - z);
        }
        else
        {
            bits.Bits <<= (int)(y - 1);
            bits.Bitpos += (int)(y - 1);
            return (int)(v >> 1);
        }
    }

    #endregion

    #region ReverseBitsArray2048

    /// <summary>
    /// Bit-reversal permutation of a 2048-element byte array.
    /// Rearranges elements so that the 11-bit index has its bits flipped.
    /// Uses SSE2 intrinsics for fast 8-way interleave.
    /// </summary>
    [SkipLocalsInit]
    public static void ReverseBitsArray2048(byte* input, byte* output)
    {
        ReadOnlySpan<byte> offsets =
        [
            0x00, 0x80, 0x40, 0xC0, 0x20, 0xA0, 0x60, 0xE0,
            0x10, 0x90, 0x50, 0xD0, 0x30, 0xB0, 0x70, 0xF0,
            0x08, 0x88, 0x48, 0xC8, 0x28, 0xA8, 0x68, 0xE8,
            0x18, 0x98, 0x58, 0xD8, 0x38, 0xB8, 0x78, 0xF8
        ];

        if (Sse2.IsSupported)
        {
            for (int i = 0; i < 32; i++)
            {
                int j = offsets[i];

                var t0 = Sse2.UnpackLow(
                    Sse2.LoadScalarVector128((long*)(input + j)).AsByte(),
                    Sse2.LoadScalarVector128((long*)(input + j + 256)).AsByte());
                var t1 = Sse2.UnpackLow(
                    Sse2.LoadScalarVector128((long*)(input + j + 512)).AsByte(),
                    Sse2.LoadScalarVector128((long*)(input + j + 768)).AsByte());
                var t2 = Sse2.UnpackLow(
                    Sse2.LoadScalarVector128((long*)(input + j + 1024)).AsByte(),
                    Sse2.LoadScalarVector128((long*)(input + j + 1280)).AsByte());
                var t3 = Sse2.UnpackLow(
                    Sse2.LoadScalarVector128((long*)(input + j + 1536)).AsByte(),
                    Sse2.LoadScalarVector128((long*)(input + j + 1792)).AsByte());

                var s0 = Sse2.UnpackLow(t0, t1);
                var s1 = Sse2.UnpackLow(t2, t3);
                var s2 = Sse2.UnpackHigh(t0, t1);
                var s3 = Sse2.UnpackHigh(t2, t3);

                t0 = Sse2.UnpackLow(s0, s1);
                t1 = Sse2.UnpackLow(s2, s3);
                t2 = Sse2.UnpackHigh(s0, s1);
                t3 = Sse2.UnpackHigh(s2, s3);

                // Store low 8 bytes and high 8 bytes to different offsets
                Sse2.StoreScalar((long*)(output), t0.AsInt64());
                Sse2.StoreScalar((long*)(output + 1024), Sse2.UnpackHigh(t0.AsInt64(), t0.AsInt64()).AsByte().AsInt64());
                Sse2.StoreScalar((long*)(output + 256), t1.AsInt64());
                Sse2.StoreScalar((long*)(output + 1280), Sse2.UnpackHigh(t1.AsInt64(), t1.AsInt64()).AsByte().AsInt64());
                Sse2.StoreScalar((long*)(output + 512), t2.AsInt64());
                Sse2.StoreScalar((long*)(output + 1536), Sse2.UnpackHigh(t2.AsInt64(), t2.AsInt64()).AsByte().AsInt64());
                Sse2.StoreScalar((long*)(output + 768), t3.AsInt64());
                Sse2.StoreScalar((long*)(output + 1792), Sse2.UnpackHigh(t3.AsInt64(), t3.AsInt64()).AsByte().AsInt64());

                output += 8;
            }
        }
        else if (AdvSimd.Arm64.IsSupported)
        {
            // ARM NEON: ZipLow/ZipHigh are the NEON equivalents of SSE2 UnpackLow/UnpackHigh
            for (int i = 0; i < 32; i++)
            {
                int j = offsets[i];

                var t0 = AdvSimd.Arm64.ZipLow(
                    Vector128.Create(*(long*)(input + j), 0).AsByte(),
                    Vector128.Create(*(long*)(input + j + 256), 0).AsByte());
                var t1 = AdvSimd.Arm64.ZipLow(
                    Vector128.Create(*(long*)(input + j + 512), 0).AsByte(),
                    Vector128.Create(*(long*)(input + j + 768), 0).AsByte());
                var t2 = AdvSimd.Arm64.ZipLow(
                    Vector128.Create(*(long*)(input + j + 1024), 0).AsByte(),
                    Vector128.Create(*(long*)(input + j + 1280), 0).AsByte());
                var t3 = AdvSimd.Arm64.ZipLow(
                    Vector128.Create(*(long*)(input + j + 1536), 0).AsByte(),
                    Vector128.Create(*(long*)(input + j + 1792), 0).AsByte());

                var s0 = AdvSimd.Arm64.ZipLow(t0.AsInt16(), t1.AsInt16()).AsByte();
                var s1 = AdvSimd.Arm64.ZipLow(t2.AsInt16(), t3.AsInt16()).AsByte();
                var s2 = AdvSimd.Arm64.ZipHigh(t0.AsInt16(), t1.AsInt16()).AsByte();
                var s3 = AdvSimd.Arm64.ZipHigh(t2.AsInt16(), t3.AsInt16()).AsByte();

                t0 = AdvSimd.Arm64.ZipLow(s0.AsInt32(), s1.AsInt32()).AsByte();
                t1 = AdvSimd.Arm64.ZipLow(s2.AsInt32(), s3.AsInt32()).AsByte();
                t2 = AdvSimd.Arm64.ZipHigh(s0.AsInt32(), s1.AsInt32()).AsByte();
                t3 = AdvSimd.Arm64.ZipHigh(s2.AsInt32(), s3.AsInt32()).AsByte();

                *(long*)(output) = t0.AsInt64().GetElement(0);
                *(long*)(output + 1024) = t0.AsInt64().GetElement(1);
                *(long*)(output + 256) = t1.AsInt64().GetElement(0);
                *(long*)(output + 1280) = t1.AsInt64().GetElement(1);
                *(long*)(output + 512) = t2.AsInt64().GetElement(0);
                *(long*)(output + 1536) = t2.AsInt64().GetElement(1);
                *(long*)(output + 768) = t3.AsInt64().GetElement(0);
                *(long*)(output + 1792) = t3.AsInt64().GetElement(1);

                output += 8;
            }
        }
        else
        {
            // Scalar fallback
            for (int i = 0; i < 2048; i++)
            {
                // Reverse the 11 bits of i
                int rev = 0;
                int val = i;
                for (int b = 0; b < 11; b++)
                {
                    rev = (rev << 1) | (val & 1);
                    val >>= 1;
                }
                output[rev] = input[i];
            }
        }
    }

    #endregion
}
