//! 11-bit LUT, 3-stream parallel canonical Huffman decoder.
//!
//! Port of src/StreamLZ/Decompression/Entropy/HuffmanDecoder{,.CodeLengths,.Decode}.cs.
//!
//! Data layout (performance notes):
//!   * `HuffRevLut` is a pair of 2048-byte arrays (Bits2Len, Bits2Sym) that together
//!     occupy exactly one 4 KB page. Aligned to 64 bytes so both arrays sit on
//!     cache-line boundaries — the hot decode loop indexes both per symbol.
//!   * `HuffReader` keeps all mutable state in one struct; the fields are ordered so
//!     the three-stream pointers/bits cluster by stream, improving register allocation
//!     in the unrolled 6-symbol-per-iteration loop below.
//!
//! Hot loop design:
//!   * Uses `[*]const u8` / `[*]u8` pointers (not slices) to avoid bounds checks on
//!     the critical path. Bounds are enforced by the outer while-loop conditions.
//!   * OR-clamps each bitpos with 0x18 post-refill to guarantee ≥24 valid bits per
//!     stream before decoding two symbols from it — matches the C# reference.

const std = @import("std");
const constants = @import("../format/streamlz_constants.zig");

// ────────────────────────────────────────────────────────────
//  Data structures
// ────────────────────────────────────────────────────────────

/// Reverse-order Huffman lookup table used by the hot decode loop.
/// Both arrays are indexed by the low 11 bits of the forward bit buffer.
/// Aligned to a cache-line boundary.
pub const HuffRevLut = extern struct {
    bits2_len: [constants.huffman_lut_size]u8 align(64) = @splat(0),
    bits2_sym: [constants.huffman_lut_size]u8 align(64) = @splat(0),
};

/// Forward-order LUT used during construction (before bit-reversal).
/// +16-byte overflow for vectorized fill safety.
pub const NewHuffLut = extern struct {
    bits2_len: [constants.huffman_lut_size + constants.huffman_lut_overflow]u8 align(64) = @splat(0),
    bits2_sym: [constants.huffman_lut_size + constants.huffman_lut_overflow]u8 align(64) = @splat(0),
};

/// Three-stream reader state for `highDecodeBytesCore`. Field order keeps
/// each stream's {src, bits, bitpos} triple adjacent for register pressure.
pub const HuffReader = struct {
    output: [*]u8,
    output_end: [*]u8,

    src: [*]const u8,
    src_bits: u32,
    src_bitpos: i32,

    src_mid: [*]const u8,
    src_mid_bits: u32,
    src_mid_bitpos: i32,

    src_end: [*]const u8,
    src_end_bits: u32,
    src_end_bitpos: i32,

    src_mid_org: [*]const u8,
};

/// Minimal bit reader for Huffman/tANS table reading. Mirrors the layout
/// of `io/bit_reader.zig::BitReader` but kept here (per the C# note) to
/// keep the Huffman hot path free of the extended API.
pub const BitReaderState = struct {
    p: [*]const u8,
    p_end: [*]const u8,
    bits: u32,
    bit_pos: i32,
};

/// Secondary byte-aligned reader used by Golomb-Rice decoding.
pub const BitReader2 = struct {
    p: [*]const u8,
    p_end: [*]const u8,
    bit_pos: u32,
};

pub const HuffRange = extern struct {
    symbol: u16,
    num: u16,
};

// ────────────────────────────────────────────────────────────
//  Constants
// ────────────────────────────────────────────────────────────

/// Canonical Huffman code-length prefix sums for lengths 0..11 (C# `CodePrefixOrg`).
pub const code_prefix_org = [_]u32{
    0x0, 0x0, 0x2, 0x6, 0xE, 0x1E, 0x3E, 0x7E, 0xFE, 0x1FE, 0x2FE, 0x3FE,
};

/// Pre-computed Golomb-Rice decoding table (value half). Entry `i` packs up to
/// four 4-bit symbols in the low nibbles and a carry count in the high nibble
/// of the MSB. Generated by enumerating all 256 possible 8-bit prefix patterns
/// for Rice parameter k=2.
pub const k_rice_code_bits2_value = [_]u32{
    0x80000000, 0x00000007, 0x10000006, 0x00000006, 0x20000005, 0x00000105, 0x10000005, 0x00000005,
    0x30000004, 0x00000204, 0x10000104, 0x00000104, 0x20000004, 0x00010004, 0x10000004, 0x00000004,
    0x40000003, 0x00000303, 0x10000203, 0x00000203, 0x20000103, 0x00010103, 0x10000103, 0x00000103,
    0x30000003, 0x00020003, 0x10010003, 0x00010003, 0x20000003, 0x01000003, 0x10000003, 0x00000003,
    0x50000002, 0x00000402, 0x10000302, 0x00000302, 0x20000202, 0x00010202, 0x10000202, 0x00000202,
    0x30000102, 0x00020102, 0x10010102, 0x00010102, 0x20000102, 0x01000102, 0x10000102, 0x00000102,
    0x40000002, 0x00030002, 0x10020002, 0x00020002, 0x20010002, 0x01010002, 0x10010002, 0x00010002,
    0x30000002, 0x02000002, 0x11000002, 0x01000002, 0x20000002, 0x00000012, 0x10000002, 0x00000002,
    0x60000001, 0x00000501, 0x10000401, 0x00000401, 0x20000301, 0x00010301, 0x10000301, 0x00000301,
    0x30000201, 0x00020201, 0x10010201, 0x00010201, 0x20000201, 0x01000201, 0x10000201, 0x00000201,
    0x40000101, 0x00030101, 0x10020101, 0x00020101, 0x20010101, 0x01010101, 0x10010101, 0x00010101,
    0x30000101, 0x02000101, 0x11000101, 0x01000101, 0x20000101, 0x00000111, 0x10000101, 0x00000101,
    0x50000001, 0x00040001, 0x10030001, 0x00030001, 0x20020001, 0x01020001, 0x10020001, 0x00020001,
    0x30010001, 0x02010001, 0x11010001, 0x01010001, 0x20010001, 0x00010011, 0x10010001, 0x00010001,
    0x40000001, 0x03000001, 0x12000001, 0x02000001, 0x21000001, 0x01000011, 0x11000001, 0x01000001,
    0x30000001, 0x00000021, 0x10000011, 0x00000011, 0x20000001, 0x00001001, 0x10000001, 0x00000001,
    0x70000000, 0x00000600, 0x10000500, 0x00000500, 0x20000400, 0x00010400, 0x10000400, 0x00000400,
    0x30000300, 0x00020300, 0x10010300, 0x00010300, 0x20000300, 0x01000300, 0x10000300, 0x00000300,
    0x40000200, 0x00030200, 0x10020200, 0x00020200, 0x20010200, 0x01010200, 0x10010200, 0x00010200,
    0x30000200, 0x02000200, 0x11000200, 0x01000200, 0x20000200, 0x00000210, 0x10000200, 0x00000200,
    0x50000100, 0x00040100, 0x10030100, 0x00030100, 0x20020100, 0x01020100, 0x10020100, 0x00020100,
    0x30010100, 0x02010100, 0x11010100, 0x01010100, 0x20010100, 0x00010110, 0x10010100, 0x00010100,
    0x40000100, 0x03000100, 0x12000100, 0x02000100, 0x21000100, 0x01000110, 0x11000100, 0x01000100,
    0x30000100, 0x00000120, 0x10000110, 0x00000110, 0x20000100, 0x00001100, 0x10000100, 0x00000100,
    0x60000000, 0x00050000, 0x10040000, 0x00040000, 0x20030000, 0x01030000, 0x10030000, 0x00030000,
    0x30020000, 0x02020000, 0x11020000, 0x01020000, 0x20020000, 0x00020010, 0x10020000, 0x00020000,
    0x40010000, 0x03010000, 0x12010000, 0x02010000, 0x21010000, 0x01010010, 0x11010000, 0x01010000,
    0x30010000, 0x00010020, 0x10010010, 0x00010010, 0x20010000, 0x00011000, 0x10010000, 0x00010000,
    0x50000000, 0x04000000, 0x13000000, 0x03000000, 0x22000000, 0x02000010, 0x12000000, 0x02000000,
    0x31000000, 0x01000020, 0x11000010, 0x01000010, 0x21000000, 0x01001000, 0x11000000, 0x01000000,
    0x40000000, 0x00000030, 0x10000020, 0x00000020, 0x20000010, 0x00001010, 0x10000010, 0x00000010,
    0x30000000, 0x00002000, 0x10001000, 0x00001000, 0x20000000, 0x00100000, 0x10000000, 0x00000000,
};

/// Pre-computed Golomb-Rice decoding table (length half). Paired with
/// `k_rice_code_bits2_value`.
pub const k_rice_code_bits2_len = [_]u8{
    0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4, 1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5,
    1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
    1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
    2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
    1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
    2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
    2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
    3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7, 4, 5, 5, 6, 5, 6, 6, 7, 5, 6, 6, 7, 6, 7, 7, 8,
};

pub const DecodeError = error{
    CorruptStream,
    SourceTruncated,
    OutputTruncated,
    BadCodeLengthFormat,
    InvalidCodeLength,
    InvalidRanges,
    LutConstructionFailed,
    StreamMismatch,
};

// ────────────────────────────────────────────────────────────
//  BitReaderState helpers (MSB-first, forward refill)
// ────────────────────────────────────────────────────────────

pub inline fn bitReaderRefill(br: *BitReaderState) void {
    while (br.bit_pos > 0) {
        const byte: u32 = if (@intFromPtr(br.p) < @intFromPtr(br.p_end)) br.p[0] else 0;
        br.bits |= byte << @intCast(br.bit_pos);
        br.bit_pos -= 8;
        br.p += 1;
    }
}

pub inline fn bitReaderReadBit(br: *BitReaderState) u32 {
    bitReaderRefill(br);
    const r = br.bits >> 31;
    br.bits <<= 1;
    br.bit_pos += 1;
    return r;
}

pub inline fn bitReaderReadBitNoRefill(br: *BitReaderState) u32 {
    const r = br.bits >> 31;
    br.bits <<= 1;
    br.bit_pos += 1;
    return r;
}

/// Reads `n` bits (n ≥ 1) without refilling.
pub inline fn bitReaderReadBitsNoRefill(br: *BitReaderState, n: u5) u32 {
    std.debug.assert(n >= 1);
    const r = br.bits >> @intCast(32 - @as(u6, n));
    br.bits <<= n;
    br.bit_pos += n;
    return r;
}

/// Reads `n` bits without refilling; `n` may be zero. Uses the two-shift
/// trick from the C# source to dodge the undefined shift-by-32 case.
pub inline fn bitReaderReadBitsNoRefillZero(br: *BitReaderState, n: u6) u32 {
    if (n == 0) return 0;
    const r = (br.bits >> 1) >> @intCast(31 - n);
    br.bits <<= @intCast(n);
    br.bit_pos += @intCast(n);
    return r;
}

/// Reads the "fluff" encoding for alphabets with fewer than 256 symbols.
pub fn bitReaderReadFluff(br: *BitReaderState, num_symbols: u32) u32 {
    if (num_symbols == 256) return 0;
    var x: u32 = 257 - num_symbols;
    if (x > num_symbols) x = num_symbols;
    x *= 2;

    const y: u32 = std.math.log2_int(u32, x - 1) + 1;
    const v: u32 = br.bits >> @intCast(32 - y);
    const z: u32 = (@as(u32, 1) << @intCast(y)) - x;

    if ((v >> 1) >= z) {
        br.bits <<= @intCast(y);
        br.bit_pos += @intCast(y);
        return v - z;
    } else {
        br.bits <<= @intCast(y - 1);
        br.bit_pos += @intCast(y - 1);
        return v >> 1;
    }
}

// ────────────────────────────────────────────────────────────
//  Golomb-Rice decoding
// ────────────────────────────────────────────────────────────

/// Decodes Golomb-Rice run lengths from a bit stream.
pub fn decodeGolombRiceLengths(dst_buf: [*]u8, size: usize, br: *BitReader2) DecodeError!void {
    var p = br.p;
    const p_end = br.p_end;
    var dst = dst_buf;
    const dst_end = dst_buf + size;

    if (@intFromPtr(p) >= @intFromPtr(p_end)) return error.SourceTruncated;

    var count: i32 = -@as(i32, @intCast(br.bit_pos));
    const initial_mask: u32 = @as(u32, 255) >> @intCast(br.bit_pos);
    var v: u32 = p[0] & initial_mask;
    p += 1;

    while (true) {
        if (v == 0) {
            count += 8;
        } else {
            const x = k_rice_code_bits2_value[v];
            // Store count + low-nibble symbols at dst[0..4]
            const lo: u32 = @as(u32, @bitCast(count)) + (x & 0x0F0F_0F0F);
            const hi: u32 = (x >> 4) & 0x0F0F_0F0F;
            std.mem.writeInt(u32, dst[0..4], lo, .little);
            std.mem.writeInt(u32, dst[4..8], hi, .little);
            dst += k_rice_code_bits2_len[v];
            if (@intFromPtr(dst) >= @intFromPtr(dst_end)) break;
            count = @intCast(x >> 28);
        }
        if (@intFromPtr(p) >= @intFromPtr(p_end)) return error.SourceTruncated;
        v = p[0];
        p += 1;
    }

    // Overshoot correction: step back by dropping trailing set bits from v.
    if (@intFromPtr(dst) > @intFromPtr(dst_end)) {
        var n: usize = @intFromPtr(dst) - @intFromPtr(dst_end);
        while (n != 0) : (n -= 1) {
            v &= v - 1;
        }
    }

    var bit_pos: u32 = 0;
    if ((v & 1) == 0) {
        p -= 1;
        const q: u32 = @ctz(v);
        bit_pos = 8 - q;
    }
    br.p = p;
    br.bit_pos = bit_pos;
}

/// Decodes additional Golomb-Rice precision bits (1, 2, or 3) and merges them
/// into the length array. Uses SIMD-style bit unpacking (u64 bit manipulation
/// tricks) — faithful port of the C# reference.
pub fn decodeGolombRiceBits(dst_buf: [*]u8, size: usize, bitcount: u32, br: *BitReader2) DecodeError!void {
    if (bitcount == 0) return;

    const dst_end = dst_buf + size;
    var p = br.p;
    const p_end = br.p_end;
    const bit_pos = br.bit_pos;

    const bits_required: u32 = @intCast(bit_pos + bitcount * @as(u32, @intCast(size)));
    const bytes_required: usize = (bits_required + 7) >> 3;
    if (bytes_required > @intFromPtr(p_end) - @intFromPtr(p)) return error.SourceTruncated;

    br.p = p + (bits_required >> 3);
    br.bit_pos = bits_required & 7;

    // Caller must guarantee 8-byte padding past dst_end.
    const bak: u64 = std.mem.readInt(u64, dst_end[0..8], .little);
    var dst = dst_buf;

    switch (bitcount) {
        1 => {
            while (@intFromPtr(dst) < @intFromPtr(dst_end)) {
                const raw: u32 = @byteSwap(std.mem.readInt(u32, p[0..4], .little));
                var bits: u64 = @as(u8, @truncate(raw >> @intCast(24 - bit_pos)));
                p += 1;
                bits = (bits | (bits << 28)) & 0x0F0000_000F;
                bits = (bits | (bits << 14)) & 0x0003_0003_0003_0003;
                bits = (bits | (bits << 7)) & 0x0101_0101_0101_0101;
                const prev = std.mem.readInt(u64, dst[0..8], .little);
                const result = prev * 2 + @byteSwap(bits);
                std.mem.writeInt(u64, dst[0..8], result, .little);
                dst += 8;
            }
        },
        2 => {
            while (@intFromPtr(dst) < @intFromPtr(dst_end)) {
                const raw: u32 = @byteSwap(std.mem.readInt(u32, p[0..4], .little));
                var bits: u64 = @as(u16, @truncate(raw >> @intCast(16 - bit_pos)));
                p += 2;
                bits = (bits | (bits << 24)) & 0x00FF_0000_00FF;
                bits = (bits | (bits << 12)) & 0x000F_000F_000F_000F;
                bits = (bits | (bits << 6)) & 0x0303_0303_0303_0303;
                const prev = std.mem.readInt(u64, dst[0..8], .little);
                const result = prev * 4 + @byteSwap(bits);
                std.mem.writeInt(u64, dst[0..8], result, .little);
                dst += 8;
            }
        },
        else => { // bitcount == 3
            while (@intFromPtr(dst) < @intFromPtr(dst_end)) {
                const raw: u32 = @byteSwap(std.mem.readInt(u32, p[0..4], .little));
                var bits: u64 = (raw >> @intCast(8 - bit_pos)) & 0xFFFFFF;
                p += 3;
                bits = (bits | (bits << 20)) & 0x0FFF_0000_0FFF;
                bits = (bits | (bits << 10)) & 0x003F_003F_003F_003F;
                bits = (bits | (bits << 5)) & 0x0707_0707_0707_0707;
                const prev = std.mem.readInt(u64, dst[0..8], .little);
                const result = prev * 8 + @byteSwap(bits);
                std.mem.writeInt(u64, dst[0..8], result, .little);
                dst += 8;
            }
        },
    }

    std.mem.writeInt(u64, dst_end[0..8], bak, .little);
}

// ────────────────────────────────────────────────────────────
//  Range conversion
// ────────────────────────────────────────────────────────────

pub fn huffConvertToRanges(
    ranges: [*]HuffRange,
    num_symbols: u32,
    p_fluff: u32,
    symlen_in: [*]const u8,
    br: *BitReaderState,
) DecodeError!u32 {
    const num_ranges: u32 = p_fluff >> 1;
    var sym_idx: i32 = 0;
    var symlen = symlen_in;

    if ((p_fluff & 1) != 0) {
        bitReaderRefill(br);
        const v: u32 = symlen[0];
        symlen += 1;
        if (v >= 8) return error.BadCodeLengthFormat;
        const extra: u5 = @intCast(v + 1);
        sym_idx = @intCast(bitReaderReadBitsNoRefill(br, extra) + (@as(u32, 1) << extra) - 1);
    }

    var syms_used: u32 = 0;
    var i: u32 = 0;
    while (i < num_ranges) : (i += 1) {
        bitReaderRefill(br);
        const v0: u32 = symlen[0];
        if (v0 >= 9) return error.BadCodeLengthFormat;
        const v0_u5: u6 = @intCast(v0);
        const num = bitReaderReadBitsNoRefillZero(br, v0_u5) + (@as(u32, 1) << @intCast(v0));
        const v1: u32 = symlen[1];
        if (v1 >= 8) return error.BadCodeLengthFormat;
        const v1_u5: u5 = @intCast(v1 + 1);
        const space = bitReaderReadBitsNoRefill(br, v1_u5) + (@as(u32, 1) << v1_u5) - 1;
        ranges[i] = .{ .symbol = @intCast(sym_idx), .num = @intCast(num) };
        syms_used += num;
        sym_idx += @intCast(num + space);
        symlen += 2;
    }

    if (sym_idx >= 256 or syms_used >= num_symbols or
        @as(u32, @intCast(sym_idx)) + num_symbols - syms_used > 256)
    {
        return error.InvalidRanges;
    }
    ranges[num_ranges] = .{ .symbol = @intCast(sym_idx), .num = @intCast(num_symbols - syms_used) };
    return num_ranges + 1;
}

// ────────────────────────────────────────────────────────────
//  Code-length table reading — "new" Golomb-Rice path
// ────────────────────────────────────────────────────────────

pub fn huffReadCodeLengthsNew(
    br: *BitReaderState,
    syms: [*]u8,
    code_prefix: [*]u32,
) DecodeError!u32 {
    const forced_bits = bitReaderReadBitsNoRefill(br, 2);
    const num_symbols = bitReaderReadBitsNoRefill(br, 8) + 1;
    const fluff = bitReaderReadFluff(br, num_symbols);

    if (num_symbols + fluff > 512) return error.BadCodeLengthFormat;

    var code_len: [512 + 16]u8 = undefined;

    var br2: BitReader2 = .{
        .p = undefined,
        .p_end = br.p_end,
        .bit_pos = @bitCast(@as(i32, @truncate((br.bit_pos - 24) & 7))),
    };
    // p = bits.P - ((24 - bits.Bitpos + 7) >> 3)
    const step_back: usize = @intCast((24 - br.bit_pos + 7) >> 3);
    br2.p = br.p - step_back;

    try decodeGolombRiceLengths(&code_len, num_symbols + fluff, &br2);

    // Zero the 16-byte tail so DecodeGolombRiceBits's bak save is safe.
    @memset(code_len[num_symbols + fluff ..][0..16], 0);

    try decodeGolombRiceBits(&code_len, num_symbols, forced_bits, &br2);

    // Reset the bit reader to br2's position.
    br.bit_pos = 24;
    br.p = br2.p;
    br.bits = 0;
    bitReaderRefill(br);
    const br2_bp: u5 = @intCast(br2.bit_pos);
    br.bits <<= br2_bp;
    br.bit_pos += @intCast(br2.bit_pos);

    // Delta-decode + sign-demap: v = -(v&1) ^ (v>>1); running sum offset.
    var running_sum: i32 = 0x1e;
    for (0..num_symbols) |i| {
        const raw: i32 = code_len[i];
        const v_signed: i32 = -(raw & 1) ^ (raw >> 1);
        const cl_signed: i32 = v_signed + (running_sum >> 2) + 1;
        if (cl_signed < 1 or cl_signed > 11) return error.InvalidCodeLength;
        code_len[i] = @intCast(cl_signed);
        running_sum += v_signed;
    }

    var range_buf: [128]HuffRange = undefined;
    const ranges_count = try huffConvertToRanges(
        &range_buf,
        num_symbols,
        fluff,
        code_len[num_symbols..].ptr,
        br,
    );
    if (ranges_count == 0) return error.InvalidRanges;

    var cp: [*]const u8 = &code_len;
    for (0..ranges_count) |i| {
        var sym: u32 = range_buf[i].symbol;
        var n: u32 = range_buf[i].num;
        while (n != 0) : (n -= 1) {
            const cl = cp[0];
            cp += 1;
            syms[code_prefix[cl]] = @intCast(sym);
            code_prefix[cl] += 1;
            sym += 1;
        }
    }

    return num_symbols;
}

// ────────────────────────────────────────────────────────────
//  Code-length table reading — "old" gamma-coded path
// ────────────────────────────────────────────────────────────

pub fn huffReadCodeLengthsOld(
    br: *BitReaderState,
    syms: [*]u8,
    code_prefix: [*]u32,
) DecodeError!u32 {
    if (bitReaderReadBitNoRefill(br) != 0) {
        var sym: u32 = 0;
        var num_symbols: u32 = 0;
        var avg_bits_x4: u32 = 32;
        const forced_bits_raw = bitReaderReadBitsNoRefill(br, 2);
        const forced_bits: u5 = @intCast(forced_bits_raw);

        const tfvgb_shift: u5 = @intCast(31 - (20 >> forced_bits));
        const thres_for_valid_gamma_bits: u32 = @as(u32, 1) << tfvgb_shift;

        var skip_zeros: bool = bitReaderReadBit(br) != 0;

        outer: while (true) {
            if (!skip_zeros) {
                if ((br.bits & 0xff000000) == 0) return error.BadCodeLengthFormat;
                const lz: u32 = @clz(br.bits);
                const n_bits: u5 = @intCast(2 * (lz + 1));
                sym += bitReaderReadBitsNoRefill(br, n_bits) - 2 + 1;
                if (sym >= 256) break :outer;
            }
            skip_zeros = false;

            bitReaderRefill(br);

            if ((br.bits & 0xff000000) == 0) return error.BadCodeLengthFormat;
            const lz_n: u32 = @clz(br.bits);
            const n_bits2: u5 = @intCast(2 * (lz_n + 1));
            var n: u32 = bitReaderReadBitsNoRefill(br, n_bits2) - 2 + 1;

            if (sym + n > 256) return error.BadCodeLengthFormat;
            bitReaderRefill(br);
            num_symbols += n;

            while (true) {
                if (br.bits < thres_for_valid_gamma_bits) return error.BadCodeLengthFormat;

                const lz3: u32 = @clz(br.bits);
                const read_bits: u5 = @intCast(lz3 + forced_bits + 1);
                const part_a = bitReaderReadBitsNoRefill(br, read_bits);
                const part_b = (lz3 - 1) << forced_bits;
                const v = part_a + part_b;
                const codelen_signed: i32 = -@as(i32, @intCast(v & 1)) ^ @as(i32, @intCast(v >> 1));
                const codelen = codelen_signed + @as(i32, @intCast((avg_bits_x4 + 2) >> 2));
                if (codelen < 1 or codelen > 11) return error.InvalidCodeLength;
                const cl: u32 = @intCast(codelen);
                avg_bits_x4 = cl + ((3 * avg_bits_x4 + 2) >> 2);
                bitReaderRefill(br);
                syms[code_prefix[cl]] = @intCast(sym);
                code_prefix[cl] += 1;
                sym += 1;
                n -= 1;
                if (n == 0) break;
            }
            if (sym == 256) break :outer;
        }

        if (sym != 256 or num_symbols < 2) return error.BadCodeLengthFormat;
        return num_symbols;
    }

    // Sparse encoding
    const num_symbols = bitReaderReadBitsNoRefill(br, 8);
    if (num_symbols == 0) return error.BadCodeLengthFormat;
    if (num_symbols == 1) {
        syms[0] = @intCast(bitReaderReadBitsNoRefill(br, 8));
    } else {
        const codelen_bits = bitReaderReadBitsNoRefill(br, 3);
        if (codelen_bits > 4) return error.BadCodeLengthFormat;
        const cl_bits_u6: u6 = @intCast(codelen_bits);
        var i: u32 = 0;
        while (i < num_symbols) : (i += 1) {
            bitReaderRefill(br);
            const s = bitReaderReadBitsNoRefill(br, 8);
            const cl_raw = bitReaderReadBitsNoRefillZero(br, cl_bits_u6) + 1;
            if (cl_raw > 11) return error.InvalidCodeLength;
            syms[code_prefix[cl_raw]] = @intCast(s);
            code_prefix[cl_raw] += 1;
        }
    }
    return num_symbols;
}

// ────────────────────────────────────────────────────────────
//  LUT construction
// ────────────────────────────────────────────────────────────

pub fn huffMakeLut(
    prefix_org: [*]const u32,
    prefix_cur: [*]const u32,
    hufflut: *NewHuffLut,
    syms: [*]const u8,
) bool {
    var cur_slot: u32 = 0;
    var i: u32 = 1;
    while (i < 11) : (i += 1) {
        const start = prefix_org[i];
        const count = prefix_cur[i] - start;
        if (count != 0) {
            const step_u5: u5 = @intCast(11 - i);
            const step_size: u32 = @as(u32, 1) << step_u5;
            const num_to_set = count << step_u5;
            if (cur_slot + num_to_set > constants.huffman_lut_size) return false;

            // Fill Bits2Len[cur_slot..cur_slot+num_to_set] with byte `i`.
            @memset(hufflut.bits2_len[cur_slot..][0..num_to_set], @intCast(i));

            // Fill Bits2Sym with the mapped symbol, block-by-block.
            var j: u32 = 0;
            var p: usize = cur_slot;
            while (j != count) : (j += 1) {
                @memset(hufflut.bits2_sym[p..][0..step_size], syms[start + j]);
                p += step_size;
            }

            cur_slot += num_to_set;
        }
    }

    const count11 = prefix_cur[11] - prefix_org[11];
    if (count11 != 0) {
        if (cur_slot + count11 > constants.huffman_lut_size) return false;
        @memset(hufflut.bits2_len[cur_slot..][0..count11], 11);
        const src_ptr = syms + prefix_org[11];
        @memcpy(hufflut.bits2_sym[cur_slot..][0..count11], src_ptr[0..count11]);
        cur_slot += count11;
    }

    return cur_slot == constants.huffman_lut_size;
}

// ────────────────────────────────────────────────────────────
//  11-bit reverse-bit permutation
// ────────────────────────────────────────────────────────────

/// Scalar 11-bit bit-reversal permutation of a 2048-byte array.
/// Runs once per decode block, not in the hot loop. Vectorizing this is a
/// Phase-7 job (`@Vector(16, u8)` + shuffle).
pub fn reverseBitsArray2048(in: [*]const u8, out: [*]u8) void {
    for (0..constants.huffman_lut_size) |i| {
        // Reverse the 11 bits of `i`.
        var rev: usize = 0;
        var val: usize = i;
        for (0..11) |_| {
            rev = (rev << 1) | (val & 1);
            val >>= 1;
        }
        out[rev] = in[i];
    }
}

// ────────────────────────────────────────────────────────────
//  3-stream parallel decode loop (the hot path)
// ────────────────────────────────────────────────────────────

pub fn highDecodeBytesCore(hr: *HuffReader, lut: *const HuffRevLut) DecodeError!void {
    var src = hr.src;
    var src_bits = hr.src_bits;
    var src_bitpos = hr.src_bitpos;

    var src_mid = hr.src_mid;
    var src_mid_bits = hr.src_mid_bits;
    var src_mid_bitpos = hr.src_mid_bitpos;

    var src_end = hr.src_end;
    var src_end_bits = hr.src_end_bits;
    var src_end_bitpos = hr.src_end_bitpos;

    var dst = hr.output;
    var dst_end = hr.output_end;

    if (@intFromPtr(src) > @intFromPtr(src_mid)) return error.StreamMismatch;

    const lut_mask: u32 = constants.huffman_lut_mask;
    const clamp: u32 = constants.huffman_bitpos_clamp_mask;

    if (@intFromPtr(hr.src_end) - @intFromPtr(src_mid) >= 4 and
        @intFromPtr(dst_end) - @intFromPtr(dst) >= 6)
    {
        dst_end -= 5;
        src_end -= 4;

        while (@intFromPtr(dst) < @intFromPtr(dst_end) and
            @intFromPtr(src) <= @intFromPtr(src_mid) and
            @intFromPtr(src_mid) <= @intFromPtr(src_end))
        {
            // Forward stream refill — read 4 bytes, shift into the bit buffer.
            const src_word: u32 = std.mem.readInt(u32, src[0..4], .little);
            src_bits |= src_word << @intCast(src_bitpos);
            src += @intCast((31 - src_bitpos) >> 3);

            // Backward stream refill — big-endian read from src_end.
            const src_end_word_le: u32 = std.mem.readInt(u32, src_end[0..4], .little);
            const src_end_word_be: u32 = @byteSwap(src_end_word_le);
            src_end_bits |= src_end_word_be << @intCast(src_end_bitpos);
            src_end -= @intCast((31 - src_end_bitpos) >> 3);

            // Middle stream refill.
            const src_mid_word: u32 = std.mem.readInt(u32, src_mid[0..4], .little);
            src_mid_bits |= src_mid_word << @intCast(src_mid_bitpos);
            src_mid += @intCast((31 - src_mid_bitpos) >> 3);

            // OR-clamp bit positions to ≥24 valid bits per stream.
            src_bitpos |= @intCast(clamp);
            src_end_bitpos |= @intCast(clamp);
            src_mid_bitpos |= @intCast(clamp);

            // 6 symbols per iteration — 2 from each stream.
            var lut_index: u32 = src_bits & lut_mask;
            var cbl: u32 = lut.bits2_len[lut_index];
            src_bits >>= @intCast(cbl);
            src_bitpos -= @intCast(cbl);
            dst[0] = lut.bits2_sym[lut_index];

            lut_index = src_end_bits & lut_mask;
            cbl = lut.bits2_len[lut_index];
            src_end_bits >>= @intCast(cbl);
            src_end_bitpos -= @intCast(cbl);
            dst[1] = lut.bits2_sym[lut_index];

            lut_index = src_mid_bits & lut_mask;
            cbl = lut.bits2_len[lut_index];
            src_mid_bits >>= @intCast(cbl);
            src_mid_bitpos -= @intCast(cbl);
            dst[2] = lut.bits2_sym[lut_index];

            lut_index = src_bits & lut_mask;
            cbl = lut.bits2_len[lut_index];
            src_bits >>= @intCast(cbl);
            src_bitpos -= @intCast(cbl);
            dst[3] = lut.bits2_sym[lut_index];

            lut_index = src_end_bits & lut_mask;
            cbl = lut.bits2_len[lut_index];
            src_end_bits >>= @intCast(cbl);
            src_end_bitpos -= @intCast(cbl);
            dst[4] = lut.bits2_sym[lut_index];

            lut_index = src_mid_bits & lut_mask;
            cbl = lut.bits2_len[lut_index];
            src_mid_bits >>= @intCast(cbl);
            src_mid_bitpos -= @intCast(cbl);
            dst[5] = lut.bits2_sym[lut_index];

            dst += 6;
        }

        dst_end += 5;
        src -= @intCast(@as(u32, @bitCast(src_bitpos)) >> 3);
        src_bitpos &= 7;
        src_end += @intCast(4 + (@as(u32, @bitCast(src_end_bitpos)) >> 3));
        src_end_bitpos &= 7;
        src_mid -= @intCast(@as(u32, @bitCast(src_mid_bitpos)) >> 3);
        src_mid_bitpos &= 7;
    }

    // Tail loop — one symbol per stream per iteration.
    while (true) {
        if (@intFromPtr(dst) >= @intFromPtr(dst_end)) break;

        // Stream 1 (forward).
        if (@intFromPtr(src_mid) - @intFromPtr(src) <= 1) {
            if (@intFromPtr(src_mid) - @intFromPtr(src) == 1) {
                src_bits |= @as(u32, src[0]) << @intCast(src_bitpos);
            }
        } else {
            const v: u32 = std.mem.readInt(u16, src[0..2], .little);
            src_bits |= v << @intCast(src_bitpos);
        }

        var lut_index: u32 = src_bits & lut_mask;
        var cbl: u32 = lut.bits2_len[lut_index];
        src_bitpos -= @intCast(cbl);
        src_bits >>= @intCast(cbl);
        dst[0] = lut.bits2_sym[lut_index];
        dst += 1;
        src += @intCast((7 - src_bitpos) >> 3);
        src_bitpos &= 7;

        if (@intFromPtr(dst) < @intFromPtr(dst_end)) {
            // Stream 2 (backward) + stream 3 (middle) refill.
            if (@intFromPtr(src_end) - @intFromPtr(src_mid) <= 1) {
                if (@intFromPtr(src_end) - @intFromPtr(src_mid) == 1) {
                    const by: u32 = src_mid[0];
                    src_end_bits |= by << @intCast(src_end_bitpos);
                    src_mid_bits |= by << @intCast(src_mid_bitpos);
                }
            } else {
                const back_ptr = src_end - 2;
                const v: u32 = std.mem.readInt(u16, back_ptr[0..2], .little);
                const v_swap: u32 = ((v >> 8) | (v << 8)) & 0xFFFF;
                src_end_bits |= v_swap << @intCast(src_end_bitpos);
                const fwd: u32 = std.mem.readInt(u16, src_mid[0..2], .little);
                src_mid_bits |= fwd << @intCast(src_mid_bitpos);
            }

            // Stream 2: backward symbol.
            lut_index = src_end_bits & lut_mask;
            cbl = lut.bits2_len[lut_index];
            dst[0] = lut.bits2_sym[lut_index];
            dst += 1;
            src_end_bitpos -= @intCast(cbl);
            src_end_bits >>= @intCast(cbl);
            src_end -= @intCast((7 - src_end_bitpos) >> 3);
            src_end_bitpos &= 7;

            if (@intFromPtr(dst) < @intFromPtr(dst_end)) {
                lut_index = src_mid_bits & lut_mask;
                cbl = lut.bits2_len[lut_index];
                dst[0] = lut.bits2_sym[lut_index];
                dst += 1;
                src_mid_bitpos -= @intCast(cbl);
                src_mid_bits >>= @intCast(cbl);
                src_mid += @intCast((7 - src_mid_bitpos) >> 3);
                src_mid_bitpos &= 7;
            }
        }

        if (@intFromPtr(src) > @intFromPtr(src_mid) or
            @intFromPtr(src_mid) > @intFromPtr(src_end))
        {
            return error.StreamMismatch;
        }
    }

    if (@intFromPtr(src) != @intFromPtr(hr.src_mid_org) or
        @intFromPtr(src_end) != @intFromPtr(src_mid))
    {
        return error.StreamMismatch;
    }
}

// ────────────────────────────────────────────────────────────
//  Top-level: Huffman type 1 / type 2 block decoder
// ────────────────────────────────────────────────────────────

/// Decodes a Huffman-coded byte block (type 1 = 2-way split, type 2 = 4-way split).
/// Writes exactly `output_size` bytes starting at `output`. Returns the number of
/// source bytes consumed (== `src.len`).
pub fn highDecodeBytesType12(
    src_in: []const u8,
    output_in: [*]u8,
    output_size: usize,
    type_: u32,
) DecodeError!usize {
    if (src_in.len == 0 or output_size == 0) return error.SourceTruncated;

    const src_start: [*]const u8 = src_in.ptr;
    const src_end: [*]const u8 = src_in.ptr + src_in.len;

    var br: BitReaderState = .{
        .p = src_start,
        .p_end = src_end,
        .bits = 0,
        .bit_pos = 24,
    };
    bitReaderRefill(&br);

    var code_prefix_org_buf: [12]u32 = code_prefix_org;
    var code_prefix_buf: [12]u32 = code_prefix_org;

    var syms_buf: [1280]u8 = undefined;
    const syms: [*]u8 = &syms_buf;

    const num_syms: u32 = blk: {
        if (bitReaderReadBitNoRefill(&br) == 0) {
            break :blk try huffReadCodeLengthsOld(&br, syms, &code_prefix_buf);
        } else if (bitReaderReadBitNoRefill(&br) == 0) {
            break :blk try huffReadCodeLengthsNew(&br, syms, &code_prefix_buf);
        } else {
            return error.BadCodeLengthFormat;
        }
    };

    if (num_syms < 1) return error.BadCodeLengthFormat;

    // Advance src past the code-length table.
    const consumed_offset: usize = @intCast(@divTrunc(24 - br.bit_pos, 8));
    var src_after_table: [*]const u8 = br.p - consumed_offset;

    // Trivial case: single symbol → memset the whole output.
    if (num_syms == 1) {
        @memset(output_in[0..output_size], syms_buf[0]);
        return src_in.len;
    }

    var huff_lut: NewHuffLut = .{};
    if (!huffMakeLut(&code_prefix_org_buf, &code_prefix_buf, &huff_lut, syms)) {
        return error.LutConstructionFailed;
    }

    var rev_lut: HuffRevLut = .{};
    reverseBitsArray2048(&huff_lut.bits2_len, &rev_lut.bits2_len);
    reverseBitsArray2048(&huff_lut.bits2_sym, &rev_lut.bits2_sym);

    if (type_ == 1) {
        if (@intFromPtr(src_after_table) + 3 > @intFromPtr(src_end)) return error.SourceTruncated;
        const split_mid: usize = @intCast(std.mem.readInt(u16, src_after_table[0..2], .little));
        src_after_table += 2;
        if (split_mid > @intFromPtr(src_end) - @intFromPtr(src_after_table)) return error.SourceTruncated;

        var hr: HuffReader = .{
            .output = output_in,
            .output_end = output_in + output_size,
            .src = src_after_table,
            .src_end = src_end,
            .src_mid_org = src_after_table + split_mid,
            .src_mid = src_after_table + split_mid,
            .src_bits = 0,
            .src_bitpos = 0,
            .src_mid_bits = 0,
            .src_mid_bitpos = 0,
            .src_end_bits = 0,
            .src_end_bitpos = 0,
        };
        try highDecodeBytesCore(&hr, &rev_lut);
    } else {
        // type 2: 4-way split
        if (@intFromPtr(src_after_table) + 6 > @intFromPtr(src_end)) return error.SourceTruncated;
        const half_output: usize = (output_size + 1) >> 1;
        const tri: u32 = std.mem.readInt(u32, src_after_table[0..4], .little) & 0xFFFFFF;
        src_after_table += 3;
        const split_mid_outer: usize = @intCast(tri);
        if (split_mid_outer > @intFromPtr(src_end) - @intFromPtr(src_after_table)) return error.SourceTruncated;

        const src_mid_outer: [*]const u8 = src_after_table + split_mid_outer;
        const split_left: usize = @intCast(std.mem.readInt(u16, src_after_table[0..2], .little));
        src_after_table += 2;

        if (@intFromPtr(src_mid_outer) - @intFromPtr(src_after_table) < split_left + 2 or
            @intFromPtr(src_end) - @intFromPtr(src_mid_outer) < 3)
        {
            return error.SourceTruncated;
        }

        const split_right: usize = @intCast(std.mem.readInt(u16, src_mid_outer[0..2], .little));
        if (@intFromPtr(src_end) - @intFromPtr(src_mid_outer + 2) < split_right + 2) return error.SourceTruncated;

        // First half
        var hr_first: HuffReader = .{
            .output = output_in,
            .output_end = output_in + half_output,
            .src = src_after_table,
            .src_end = src_mid_outer,
            .src_mid_org = src_after_table + split_left,
            .src_mid = src_after_table + split_left,
            .src_bits = 0,
            .src_bitpos = 0,
            .src_mid_bits = 0,
            .src_mid_bitpos = 0,
            .src_end_bits = 0,
            .src_end_bitpos = 0,
        };
        try highDecodeBytesCore(&hr_first, &rev_lut);

        // Second half
        const second_src: [*]const u8 = src_mid_outer + 2;
        var hr_second: HuffReader = .{
            .output = output_in + half_output,
            .output_end = output_in + output_size,
            .src = second_src,
            .src_end = src_end,
            .src_mid_org = second_src + split_right,
            .src_mid = second_src + split_right,
            .src_bits = 0,
            .src_bitpos = 0,
            .src_mid_bits = 0,
            .src_mid_bitpos = 0,
            .src_end_bits = 0,
            .src_end_bitpos = 0,
        };
        try highDecodeBytesCore(&hr_second, &rev_lut);
    }

    return src_in.len;
}

// ────────────────────────────────────────────────────────────
//  Tests
// ────────────────────────────────────────────────────────────

const testing = std.testing;

test "code_prefix_org values match C# source" {
    try testing.expectEqual(@as(u32, 0x0), code_prefix_org[0]);
    try testing.expectEqual(@as(u32, 0x0), code_prefix_org[1]);
    try testing.expectEqual(@as(u32, 0x2), code_prefix_org[2]);
    try testing.expectEqual(@as(u32, 0x3FE), code_prefix_org[11]);
}

test "k_rice_code_bits2_value matches C# table length" {
    try testing.expectEqual(@as(usize, 256), k_rice_code_bits2_value.len);
    try testing.expectEqual(@as(u32, 0x80000000), k_rice_code_bits2_value[0]);
    try testing.expectEqual(@as(u32, 0x00000000), k_rice_code_bits2_value[255]);
}

test "k_rice_code_bits2_len matches C# table" {
    try testing.expectEqual(@as(usize, 256), k_rice_code_bits2_len.len);
    try testing.expectEqual(@as(u8, 0), k_rice_code_bits2_len[0]);
    try testing.expectEqual(@as(u8, 8), k_rice_code_bits2_len[255]);
}

test "reverseBitsArray2048 permutes correctly" {
    var in_buf: [constants.huffman_lut_size]u8 align(64) = undefined;
    var out_buf: [constants.huffman_lut_size]u8 align(64) = @splat(0);
    for (&in_buf, 0..) |*b, i| b.* = @truncate(i);

    reverseBitsArray2048(&in_buf, &out_buf);

    // out[rev(i)] == in[i] == (i & 0xFF). Verify a few known reversals.
    // bit-reverse of 0 in 11 bits = 0
    try testing.expectEqual(@as(u8, 0), out_buf[0]);
    // bit-reverse of 1 (0b00000000001) = 0b10000000000 = 1024
    try testing.expectEqual(@as(u8, 1), out_buf[1024]);
    // bit-reverse of 0b00000000010 = 0b01000000000 = 512
    try testing.expectEqual(@as(u8, 2), out_buf[512]);
    // bit-reverse of 0b11111111111 = 0b11111111111 = 2047
    try testing.expectEqual(@as(u8, 2047 & 0xFF), out_buf[2047]);
}

test "bitReaderRefill forward mirrors io/bit_reader" {
    const data = [_]u8{ 0xAB, 0xCD, 0xEF, 0x12 };
    var br: BitReaderState = .{ .p = data[0..].ptr, .p_end = data[0..].ptr + data.len, .bits = 0, .bit_pos = 24 };
    bitReaderRefill(&br);
    try testing.expectEqual(@as(u32, 0xABCDEF00), br.bits);
    try testing.expectEqual(@as(i32, 0), br.bit_pos);
}

test "HuffRevLut is 64-byte aligned and 4096 bytes" {
    try testing.expectEqual(@as(usize, 4096), @sizeOf(HuffRevLut));
    try testing.expectEqual(@as(usize, 64), @alignOf(HuffRevLut));
}
